refactor : add constructor to PostalTradeAddress
cs-kmitl-2017/group4 pull request #11
Opened 2017-12-07 15:19 UTC by mindelf

2017-12-07 16:26 UTC, champillon requested changes
ฝากชี้แจงมาด้วยครับ

2017-12-07 16:26 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/PostalTradeAddress.java
> +    public PostalTradeAddress(String lineOne,
ไม่มี test หรอครับ???

2017-12-07 16:26 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/PostalTradeAddress.java
> +    public PostalTradeAddress() {
ทำไมต้องมี constructor 2อัน ที่ override กันด้วยครับ?

2017-12-07 16:53 UTC, mindelf commented on src/main/java/th/ac/kmitl/science/comsci/example/models/PostalTradeAddress.java
> +    public PostalTradeAddress() {
ต้องการที่จะทำเป็น JavaBean เพื่อ เผื่อเอาเข้าไปใช้ใน JSP ค่ะ

2017-12-07 17:05 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/PostalTradeAddress.java
> +    public PostalTradeAddress() {
Ok ครับ

2017-12-08 01:19 UTC, champillon approved these changes
LTGM la

2017-12-08 02:08 UTC, khemtat requested changes

2017-12-08 02:08 UTC, khemtat commented on src/test/java/th/ac/kmitl/science/comsci/example/models/PostalTradeAddressTest.java
> +        assertEquals("Pasthiyakan Kaewpitak",ConstructorPostalTradeAddress.getLineOne());
มีตัวแปรอยู่แล้วด้านบน ไม่ควรใช้ raw string นะครับ เอาตัวแปรมาเทียบค่าน่าจะดีกว่าไหมครับ แล้วก็หลังเครื่องหมายคอมมา , เคาะ spacebar 1 ครั้งนะครับ

2017-12-08 03:56 UTC, khemtat approved these changes

2017-12-08 03:57 UTC, merged

2017-12-08 05:28 UTC, champillon commented
ตัด คะแนนดังนี้ครับ
- 0.25 คะแนน ไม่เพราะไม่เคาะ space
- 0.25 คะแนน เพราะเขียน commit log ไม่ละเอียดครับ จริงๆไฟล์ไหนแก้อะไรก็เขียน commit log แบบนั้นไปครับ

@mindelf