Features: create TradeProduct model and TradeProductTest
cs-kmitl-2017/group4 pull request #14
Opened 2017-12-08 14:58 UTC by panuwich321

create TradeProduct.java
create TradeProductTest.java

2017-12-08 15:10 UTC, champillon requested changes
แก้ไขมาด้วยครับ

2017-12-08 15:10 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/TradeProduct.java
> +    private String id;
เว้นบรรทัด ด้วยครับ ระหว่างชื่อ class กับ attribute ตัวแรก

2017-12-08 15:10 UTC, champillon commented on src/test/java/th/ac/kmitl/science/comsci/example/models/TradeProductTest.java
> +        String name = "Richard Mille RM 30 Le Mans Classic";
"Richard Mille RM 30 Le Mans Classic" อันนี้คืออะไรครับ เอาอะไรที่เป็น Product ทั่วไป เช่น Pepsi ดีกว่ามั้ย

2017-12-08 15:11 UTC, panuwich321 commented on src/test/java/th/ac/kmitl/science/comsci/example/models/TradeProductTest.java
> +        String name = "Richard Mille RM 30 Le Mans Classic";
โอเคครับ

2017-12-08 15:28 UTC, champillon approved these changes
LGTM la

2017-12-08 15:30 UTC, mahasak requested changes
Please refactor test a bit more

2017-12-08 15:30 UTC, mahasak commented on src/test/java/th/ac/kmitl/science/comsci/example/models/TradeProductTest.java
> +    public void testGetName() {
These 3 test can be merge, why we need 3 test to just test getting and setting property ?

2017-12-09 05:28 UTC, thebankky approved these changes
LGTM krub

2017-12-09 05:48 UTC, merged