feature : create Profile abstract class
cs-kmitl-2017/group4 pull request #7
Opened 2017-11-26 10:06 UTC by OwariNeko

2017-11-27 00:53 UTC, champillon requested changes
Please describe which case do your friend inherit this class

2017-11-27 00:53 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Profile.java
> +    protected String id;
Add one blank line between class name and first variable declaration

2017-12-03 14:04 UTC, champillon requested changes
แก้ด้วยครับ สู้ๆนะครับ ^^b

2017-12-03 14:04 UTC, champillon commented on src/test/java/th/ac/kmitl/science/comsci/example/models/BuyerTest.java
> +    public void TestgetId() {
method ขึ้นต้นด้วยตัวเล็กครับ

2017-12-03 14:04 UTC, champillon commented on src/test/java/th/ac/kmitl/science/comsci/example/models/BuyerTest.java
> +    @Test
เว้นบรรทัดด้วยครับ

2017-12-03 14:04 UTC, champillon commented on src/test/java/th/ac/kmitl/science/comsci/example/models/BuyerTest.java
> +        assertEquals(Testinputdata.getTaxId(), "123");
ข้อมูล Test ควรใส่ให้สมจริงครับ เช่นเป็น เลขประจำตัวผู้เสียภาษี ก็ควร mock ข้อมูลเลขประจำตัวผู้เสียภาษีมาครับ

2017-12-03 14:04 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Profile.java
> +public abstract class Profile {
ทำไมตั้งชื่อว่า Profile ครับ

2017-12-03 14:04 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Profile.java
> +    protected String id;
แล้วทำไมไม่ใส่ getter/setter ไว้ในนี้เลยครับ ไปใส่ใน Buyer เพราะอะไรครับ

2017-12-03 14:04 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Buyer.java
> +public class Buyer extends Profile{
Buyer กับ Seller นั้น data structure เดียวกันรึป่าวครับ ถ้าเหมือนกัน ไม่จำเป็นต้องทำเป็น abstract class ก็ได้ครับ

2017-12-07 08:08 UTC, champillon requested changes
แก้ไขย่อหน้าให้ตรงกันด้วยนะครับ

2017-12-07 08:08 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Company.java
> +	String id;
ต่อหน้าไม่ตรงกับชื่อ method ครับ

2017-12-07 08:35 UTC, champillon requested changes
แก้ไขด้วยนะครับ

2017-12-07 08:35 UTC, champillon commented on src/test/java/th/ac/kmitl/science/comsci/example/models/CompanyTest.java
> +	Company Testinputdata = new Company();
อันนี้ ปรับให้ตรงกันด้วยสิครับ

2017-12-07 08:36 UTC, OwariNeko commented on src/test/java/th/ac/kmitl/science/comsci/example/models/CompanyTest.java
> +	Company Testinputdata = new Company();
ลืมครับ

2017-12-07 09:15 UTC, champillon approved these changes
LGTM la

2017-12-07 09:21 UTC, khemtat commented on src/test/java/th/ac/kmitl/science/comsci/example/models/CompanyTest.java
> +	Company Testinputdata = new Company();
@OwariNeko อย่าลืมแก้ชื่อตัวแปรนะครับ พี่รู้สึกว่าเราควรตั้งชื่อให้มันสื่อกับคลาสมากกว่านี้นิดนึงเนอะ

มันเป็น
```java
Company Testinputdata = new Company();
```
หากเป็นพี่ พี่คงตั้งว่าเป็น
```java
Company company = new Company();
```
มันจะเหมาะกว่ามั้ยครับ อ่านแล้วเข้าใจง่ายด้วย หรือมีเหตุผลอื่นที่จะใช้ชื่อแบบเดิมไหมครับ

2017-12-07 09:40 UTC, khemtat approved these changes
LGTM krub.

2017-12-07 09:41 UTC, merged

2017-12-07 09:57 UTC, champillon commented
ให้คะแนนตามนี้ครับ

1. design as component (0.75 คะแนน) => buyer กับ seller ใช้ data structure เหมือนกัน แต่ตอนแรก สร้างเป็น class แยกกันเลยตัด 0.25 คะแนน

2. naming & convention (0.75 คะแนน) => code ไม่จัดให้ align กันครับ ตัด 0.25 คะแนน

3. technology (0 คะแนน) => ไม่ได้ใช้อะไรยากเลยครับ เพราะ refactor จาก PR ก่อน

4. git usage (1 คะแนน) => commit log เขียนได้เรียบร้อยดีครับ

ทำ PR อื่นที่ยากๆกว่านี้มาดีกว่าครับ จะได้ review และให้คะแนนได้เยอะกว่านี้
@OwariNeko